In [1]:
import pandas as pd 
file_path = './tuning_results/tune_19/result/tuning_result_tfbind8_lr0.05.csv' 
df = pd.read_csv(file_path) 
df = df.sort_values(by='mean (100th)',ascending=False)
df = df[df['mean (100th)']>0.95]
print(len(df))
df

367


sampling_lr  lengthscale  delta   eta  alpha  \
796         0.01            5   0.25  1.00   0.65   
795         0.01            5   0.25  1.00   0.60   
798         0.01            5   0.25  1.00   0.75   
799         0.01            5   0.25  1.00   0.80   
286         0.01            5   0.25  0.15   0.65   
..           ...          ...    ...   ...    ...   
141         0.01            5   0.25  0.05   0.90   
447         0.01            5   0.25  0.20   1.20   
686         0.01            5   0.25  0.50   1.00   
231         0.01            5   0.25  0.10   0.90   
108         0.01            5   0.25  0.05   0.75   

     classifier_free_guidance_weight  mean (100th)  std (100th)  mean (80th)  \
796                             -1.5      0.980214     0.012559     0.695330   
795                             -1.5      0.978915     0.011678     0.692849   
798                             -1.5      0.976951     0.012204     0.697829   
799                             -1.5      0.975638     0.012236     0.701586   
286                             -3.5      0.975060     0.020043     0.699730   
..                               ...           ...          ...          ...   
141                             -2.5      0.950047     0.028867     0.696154   
447                             -1.5      0.950031     0.029229     0.698741   
686                             -2.5      0.950010     0.032563     0.709562   
231                             -2.5      0.950002     0.028816     0.695214   
108                             -3.5      0.950001     0.026411     0.702284   

     std (80th)  mean (50th)  std (50th)  
796    0.033445     0.531323    0.009672  
795    0.033678     0.529701    0.012016  
798    0.037306     0.531826    0.013205  
799    0.028077     0.533245    0.014702  
286    0.058520     0.531604    0.042001  
..          ...          ...         ...  
141    0.058606     0.534761    0.040126  
447    0.072006     0.543143    0.040471  
686    0.059402     0.537664    0.032119  
231    0.061696     0.535783    0.039138  
108    0.051896     0.544033    0.045836  

[367 rows x 12 columns]

In [3]:
import pandas as pd 
import numpy as np 

num_fit_samples_list = [10000,12000,13000,14000,15000,16000,17000,18000] 
best_tf8_hyper = None 
for num_fit_samples in num_fit_samples_list: 
    best_tf8_hyper1 =  pd.read_csv(f'tuning_results/tune_23/result/tuning_result_tfbind8_num_fit_samples{num_fit_samples}_lengthscale5.75_sampling_lr0.05_delta0.25.csv')
    best_tf8_hyper1 = best_tf8_hyper1[best_tf8_hyper1['mean (100th)']>0.9795]
    best_tf8_hyper = pd.concat([best_tf8_hyper,best_tf8_hyper1])
best_tf8_hyper = best_tf8_hyper.sort_values(by= 'mean (100th)',ascending= False)
# best_tf8_hyper.head(50)
best_tf8_hyper = best_tf8_hyper[['eta', 'alpha', 'classifier_free_guidance_weight']].to_numpy()
best_tf8_hyper = np.unique(best_tf8_hyper,axis=0)
print(len(best_tf8_hyper))
best_tf8_hyper

149


array([[ 0.  ,  0.8 , -3.  ],
       [ 0.  ,  0.8 , -2.5 ],
       [ 0.  ,  0.8 , -2.  ],
       [ 0.  ,  0.8 , -1.5 ],
       [ 0.  ,  0.85, -3.  ],
       [ 0.  ,  0.85, -2.5 ],
       [ 0.  ,  0.85, -2.  ],
       [ 0.  ,  0.85, -1.5 ],
       [ 0.  ,  0.9 , -3.  ],
       [ 0.  ,  0.9 , -2.5 ],
       [ 0.  ,  0.9 , -2.  ],
       [ 0.  ,  0.9 , -1.5 ],
       [ 0.  ,  0.95, -3.  ],
       [ 0.  ,  0.95, -2.5 ],
       [ 0.  ,  0.95, -2.  ],
       [ 0.  ,  0.95, -1.5 ],
       [ 0.  ,  1.  , -3.  ],
       [ 0.  ,  1.  , -2.5 ],
       [ 0.  ,  1.  , -2.  ],
       [ 0.  ,  1.  , -1.5 ],
       [ 0.05,  0.8 , -3.  ],
       [ 0.05,  0.8 , -2.5 ],
       [ 0.05,  0.8 , -2.  ],
       [ 0.05,  0.8 , -1.5 ],
       [ 0.05,  0.85, -3.  ],
       [ 0.05,  0.85, -2.5 ],
       [ 0.05,  0.85, -2.  ],
       [ 0.05,  0.85, -1.5 ],
       [ 0.05,  0.9 , -3.  ],
       [ 0.05,  0.9 , -2.5 ],
       [ 0.05,  0.9 , -2.  ],
       [ 0.05,  0.9 , -1.5 ],
       [ 0.05,  0.95, -2.5 ],
       [ 0

In [10]:
import pandas as pd 

best_tf10_hyper = pd.read_csv('./tuning_results/tune_23/result/tuning_result_tfbind10_lengthscale6.5_sampling_lr0.05_delta0.25.csv')
best_tf10_hyper = best_tf10_hyper[best_tf10_hyper['mean (100th)']>0.65]
# best_tf8_hyper = None
# for num_fit_samples in  [10000,12000,13000,14000,15000,16000,17000,18000] : 
#     best_tf8_hyper1 = pd.read_csv(f'./tuning_results/tune_23/result/tuning_result_tfbind8_num_fit_samples{num_fit_samples}_lengthscale5.75_sampling_lr0.05_delta0.25.csv')
#     best_tf8_hyper1 = best_tf8_hyper1[best_tf8_hyper1['mean (100th)']>0.97] 
#     best_tf8_hyper = pd.concat([best_tf8_hyper1,best_tf8_hyper],ignore_index=True) 
# best_tf8_hyper = best_tf8_hyper.merge(best_tf10_hyper, on= ['sampling_lr','lengthscale','delta','eta','alpha','classifier_free_guidance_weight'])
# best_tf8_hyper
best_tf10_hyper
                        

Empty DataFrame
Columns: [num_fit_samples, sampling_lr, lengthscale, delta, eta, alpha, classifier_free_guidance_weight, mean (100th), std (100th), mean (80th), std (80th), mean (50th), std (50th)]
Index: []

In [5]:
import pandas as pd 

best_tf10_hyper = pd.read_csv('./tuning_results/tune_22_100steps/result/tuning_result_tfbind10_num_fit_samples10000_lengthscale6.0_sampling_lr0.05_delta0.25.csv')
best_tf10_hyper = best_tf10_hyper[best_tf10_hyper['mean (100th)']>0.67]
best_tf8_hyper  = pd.read_csv('./tuning_results/tune_20/result/tuning_result_tfbind8_lengthscale6.0_sampling_lr0.05_delta0.25.csv')
best_tf8_hyper.merge(best_tf10_hyper, on = ['sampling_lr','eta','alpha','delta','lengthscale','classifier_free_guidance_weight'])
                        

sampling_lr  lengthscale  delta  eta  alpha  \
0         0.05          6.0   0.25  1.0   0.95   
1         0.05          6.0   0.25  1.0   0.90   
2         0.05          6.0   0.25  1.0   0.95   

   classifier_free_guidance_weight  mean (100th)_x  std (100th)_x  \
0                             -3.5        0.972493       0.013150   
1                             -1.5        0.972346       0.012561   
2                             -1.5        0.972346       0.012561   

   mean (80th)_x  std (80th)_x  mean (50th)_x  std (50th)_x  mean (100th)_y  \
0       0.722989      0.022152       0.550731      0.020362        0.688608   
1       0.782287      0.019385       0.598184      0.015772        0.672451   
2       0.781039      0.021043       0.601366      0.018304        0.672451   

   std (100th)_y  mean (80th)_y  std (80th)_y  mean (50th)_y  std (50th)_y  
0        0.11929       0.515397      0.007976       0.463829      0.007172  
1        0.12612       0.524252      0.006357       0.469914      0.008129  
2        0.12612       0.523236      0.005811       0.470035      0.008192

In [14]:

import torch 
import random
import numpy as np 

def set_random_seed(SEED=1234):
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


set_random_seed(0) 
set_random_seed(0)
print(torch.randint(1,10,(10,))) 
print(1)
set_random_seed(1) 
print(torch.randint(1,10,(10,)))
set_random_seed(0) 
print(torch.randint(1,10,(10,)))
set_random_seed(1) 
print(torch.randint(1,10,(10,)))

tensor([9, 1, 3, 7, 8, 7, 8, 2, 2, 1])
1
tensor([5, 6, 1, 6, 8, 2, 3, 6, 9, 1])
tensor([9, 1, 3, 7, 8, 7, 8, 2, 2, 1])
tensor([5, 6, 1, 6, 8, 2, 3, 6, 9, 1])


In [27]:
import torch

# Create offline_y with duplicate values, and some values repeating in a specific order
offline_y = torch.tensor([1.0, 2.0, 3.0, 3.0, 2.0, 1.0, 5.0, 4.0, 5.0, 4.0])
offline_x = torch.arange(len(offline_y))  # For simplicity, x is just indices [0, 1, 2, ...]

# First code:
sorted_indices = torch.argsort(offline_y)[-5:]  # Top 5 largest elements
offline_x_1 = offline_x[sorted_indices]
offline_y_1 = offline_y[sorted_indices]

# Re-sorting the top 5 largest elements
indices_1 = torch.argsort(offline_y_1)
offline_x_1 = offline_x_1[indices_1]
offline_y_1 = offline_y_1[indices_1]

print(f"First Code - offline_x_1: {offline_x_1}, offline_y_1: {offline_y_1}")

# Second code:
indices_2 = torch.argsort(offline_y)
offline_x_2 = offline_x[indices_2]
offline_y_2 = offline_y[indices_2]

# Selecting the top 5 largest elements
offline_x_2 = offline_x_2[-5:]
offline_y_2 = offline_y_2[-5:]

print(f"Second Code - offline_x_2: {offline_x_2}, offline_y_2: {offline_y_2}")

# Check if outputs are identical
print(torch.equal(offline_x_1, offline_x_2))  # Check if offline_x are the same
print(torch.equal(offline_y_1, offline_y_2))  # Check if offline_y are the same


First Code - offline_x_1: tensor([3, 7, 9, 6, 8]), offline_y_1: tensor([3., 4., 4., 5., 5.])
Second Code - offline_x_2: tensor([3, 7, 9, 6, 8]), offline_y_2: tensor([3., 4., 4., 5., 5.])
True
True


In [12]:
import pandas as pd 

best_tf10_hyper = pd.read_csv('./tuning_results/tune_22_100steps/result/tuning_result_tfbind10_num_fit_samples10000_lengthscale6.0_sampling_lr0.05_delta0.25.csv')
best_tf10_hyper = best_tf10_hyper[best_tf10_hyper['mean (100th)']>0.67]
best_tf8_hyper = None

best_tf8_hyper1 = pd.read_csv(f'./tuning_results/tune_20/result/tuning_result_tfbind8_lengthscale6.0_sampling_lr0.05_delta0.25.csv')
best_tf8_hyper1 = best_tf8_hyper1[best_tf8_hyper1['mean (100th)']>0.97] 
best_tf8_hyper = pd.concat([best_tf8_hyper1,best_tf8_hyper],ignore_index=True) 
best_tf8_hyper = best_tf8_hyper.merge(best_tf10_hyper, on= ['sampling_lr','lengthscale','delta','eta','alpha','classifier_free_guidance_weight'])
best_tf8_hyper
                        

sampling_lr  lengthscale  delta  eta  alpha  \
0         0.05          6.0   0.25  1.0   0.95   
1         0.05          6.0   0.25  1.0   0.90   
2         0.05          6.0   0.25  1.0   0.95   

   classifier_free_guidance_weight  mean (100th)_x  std (100th)_x  \
0                             -3.5        0.972493       0.013150   
1                             -1.5        0.972346       0.012561   
2                             -1.5        0.972346       0.012561   

   mean (80th)_x  std (80th)_x  mean (50th)_x  std (50th)_x  mean (100th)_y  \
0       0.722989      0.022152       0.550731      0.020362        0.688608   
1       0.782287      0.019385       0.598184      0.015772        0.672451   
2       0.781039      0.021043       0.601366      0.018304        0.672451   

   std (100th)_y  mean (80th)_y  std (80th)_y  mean (50th)_y  std (50th)_y  
0        0.11929       0.515397      0.007976       0.463829      0.007172  
1        0.12612       0.524252      0.006357       0.469914      0.008129  
2        0.12612       0.523236      0.005811       0.470035      0.008192

In [2]:
import pandas as pd
best_ant_hyper = pd.read_csv('tuning_results/tune_23/result/tuning_result_ant_lengthscale1.0_sampling_lr0.001_delta0.25.csv')
best_ant_hyper = best_ant_hyper[best_ant_hyper['mean (100th)']>0.96]
#best_ant_hyper = best_ant_hyper[best_ant_hyper['alpha']==0.7]
#best_ant_hyper = best_ant_hyper[best_ant_hyper['eta']==0.05]
best_dkitty_hyper = pd.read_csv('tuning_results/tune_23/result/tuning_result_dkitty_lengthscale1.0_sampling_lr0.001_delta0.25.csv')
best_dkitty_hyper = best_dkitty_hyper[best_dkitty_hyper['mean (100th)']>0.96]
best_dkitty_hyper.merge(best_ant_hyper,on=['sampling_lr','lengthscale','delta','eta','alpha','classifier_free_guidance_weight'])


sampling_lr  lengthscale  delta   eta  alpha  \
0        0.001          1.0   0.25  0.00   0.90   
1        0.001          1.0   0.25  0.10   0.90   
2        0.001          1.0   0.25  0.15   0.90   
3        0.001          1.0   0.25  0.00   0.95   
4        0.001          1.0   0.25  0.15   0.95   

   classifier_free_guidance_weight  mean (100th)_x  std (100th)_x  \
0                             -1.5        0.974948       0.006262   
1                             -1.5        0.972686       0.004727   
2                             -1.5        0.972997       0.005703   
3                             -1.5        0.976521       0.006033   
4                             -1.5        0.974561       0.005463   

   mean (80th)_x  std (80th)_x  mean (50th)_x  std (50th)_x  mean (100th)_y  \
0       0.940174      0.001529       0.920466      0.001728        0.962280   
1       0.939653      0.002457       0.919721      0.001889        0.960336   
2       0.938327      0.002117       0.918957      0.003386        0.961577   
3       0.939601      0.002839       0.919563      0.001926        0.968040   
4       0.938629      0.002856       0.918862      0.002647        0.960828   

   std (100th)_y  mean (80th)_y  std (80th)_y  mean (50th)_y  std (50th)_y  
0       0.020133       0.841277      0.010205       0.720924      0.017192  
1       0.012124       0.845797      0.013438       0.720395      0.009260  
2       0.011467       0.837854      0.011569       0.716856      0.008143  
3       0.016637       0.836664      0.009735       0.714163      0.014818  
4       0.012349       0.840807      0.012997       0.711411      0.018942

In [2]:
n='abc'
x = f'{n}12'
x

'abc12'